### ISSUE TITLE
Issues with End of Line Sequence CRLF

### ISSUE THREAD

**Issue by KerberosMorphy** [bukowskiadam/reveal-md-multifile#1]
Hi, really nice works!

I was developing a reveal-md template and I had some issues with the slides from other files not loading.

The issues was because my file is set `CRLF` instead of `LF`.

I have the option of converting them to `LF` or editing a little bit your `preprocess.js` to handle both case.

Here the change, feel free to use it if you find it useful:

```diff
- const FILE_REF_REGEX = /^FILE: (.+)$/;
+ const FILE_REF_REGEX = /^FILE: (.+)\r?$/;
```

**Comment by bukowskiadam** [comment]
Thanks! I've applied a fix. TBH it's been a long time since I've updated this "project", but I'm glad that it's still useful for someone!

**Comment by bukowskiadam** [comment]
And I've updated deps as well. Cheers!
